name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  push_to_docker_hub:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        id: login_docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Echo GitHub SHA
        run: echo $GITHUB_SHA

      - name: Build and push multi-platform Docker image
        id: build_and_push_image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER_NAME }}/node-red-custom:latest
            ${{ secrets.DOCKER_HUB_USER_NAME }}/node-red-custom:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.build_and_push_image.outputs.created }}

      - name: Logout from Docker Hub
        run: docker logout

      - name: End
        run: echo "Docker image pushed to Docker Hub successfully"